name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: warchant/setup-sonar-scanner@v7   

      - name: SonarQube Scan
        run: mvn sonar:sonar
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
